### ISSUE TITLE
considering adding toolktip to each elements

### ISSUE THREAD

**Issue by Trickee** [alesmit/jquery-hortree#1]
hi, 

 have you considered adding tooltip to each elements?

**Comment by alesmit** [comment]
Hello Trickee,

I can do that. I can add a property to the base object called `tooltip`, its content will be shown hovering on each element. What do you think about this approach?

**Comment by Trickee** [comment]
@alesmit 
Hi, alesmit

good thoughts, have a try!!

**Comment by alesmit** [comment]
@Trickee 

I just updated the project ;)
