### ISSUE TITLE
bad arrows positioning

### ISSUE THREAD

**Issue by v0lume** [alesmit/jquery-hortree#2]
hi!
i think there is a bug with arrows positioning. it always calculate position from left corner of window, not container.
![image](https://cloud.githubusercontent.com/assets/5075100/25599512/4399e284-2ee5-11e7-9bba-ba375e6150f9.png)

**Comment by alesmit** [comment]
Hello @v0lume 
I am going to investigate about this, could you give me info about how to reproduce that problem?

thank you

**Comment by v0lume** [comment]
@alesmit quick example - u can create markup like this (bootstrap). i don't check this but it should reproduce the issue
```
<div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-9">
        <div class="my-container"></div>
    </div>
<div>
```
where `.my-container` is initial container for hortree

the problem is in `getPos(el)` function. you should check whether we are outside of our hortree container or not. quick fix:

```
function getPos(el) {
    var lx = 0,
          ly = 0;

    while (el != null) {
        lx += el.offsetLeft;
        ly += el.offsetTop;
        el = el.offsetParent;

        if ($('.hortree-wrapper').is(el)) {
            break;
        }
    }

    return {x: lx, y: ly};
}
```

**Comment by alesmit** [comment]
@v0lume thank you. I updated the source code, your fix worked well!

ps. I suggest to open a pull request next time so you can contribute directly on the project! 😉
